/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Model.glb --transform 
Files: Model.glb [1.93MB] 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/native'

/**
 * Composant Model : Charge et affiche un modèle 3D à partir d'un fichier GLB transformé.
 * @param {Object} props - Propriétés optionnelles pour le composant.
 * @returns {JSX.Element} Composant React représentant le modèle 3D.
 */

export function Model(props) {
  // Utilisation du hook useGLTF pour charger le modèle 3D
  const { nodes, materials } = useGLTF('./Model-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.703, 0, 0]}>
        <mesh geometry={nodes.Body1.geometry} material={materials.Char_lp} />
        <mesh geometry={nodes.Body1_1.geometry} material={materials.Eye} />
        <mesh geometry={nodes.Body1_2.geometry} material={materials.Eyel} />
      </group>
      <mesh geometry={nodes.Char_Mlp.geometry} material={materials.Char_Mlp} position={[0.717, 0, 0]} />
    </group>
  )
}

// Préchargement du modèle 3D pour améliorer les performances
useGLTF.preload('./model.gltf')
